#!/usr/bin/env bash
cd NEON
echo -e "\e[33m          \e[0m"
echo -e "\e[33m          \e[0m"
echo -e "\e[33m          \e[0m"
echo -e "\e[33m           \e[0m"
echo -e "\e[33m           \e[0m"
while(true) do
lua start.lua 
done
